name: Build - Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      HUSKY: 0
      NODE_VERSION: "14"
      NPM_TOKEN: ${{ secrets.SERVICE_ACCT_TOKEN }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          token: ${{secrets.SERVICE_ACCT_TOKEN}}

      - name: Setup Node.js for Build
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://npm.pkg.github.com/

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-${{ env.NODE_VERSION }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.NODE_VERSION }}-

      - name: Install package dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

